name: PerfCake
title: PerfCake -- A Lightweight Performance Testing Framework
org: PerfCake.org
base_url: '.'
profiles:
  development:
    base_url: '.'
  production:
    base_url: 'http://www.perfcake.org'