name: PerfCake
title: PerfCake -- A Lightweight Performance Testing Framework
org: PerfCake.org
version: unknown-SNAPSHOT
base_url: '.'
profiles:
  development:
    base_url: '/'
  production:
    base_url: 'https://www.perfcake.org'